on:
  push:
    branches:
      - master
      - gh-pages-*
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Prepare for building'
        run: |
          # Add readme and changelog
          tail -n +8 README.md | sed 's/## /# /g' >> website/content/_index.md
          tail -n +3 CHANGELOG.md | sed 's/## /# /g' >> website/content/CHANGELOG.md
      - name: 'Build and deploy'
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: website
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
